# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Marko Putnikovic
description:
baseurl: "" # the subpath of the site
url: "putnich.github.io" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.jpg

header:
  pages:
    - name: Home
      slug: /
    - name: Research
    #- name: Blog

footer:
  show_copyright: true
  contact:
    - name: Email
      value: marko.putnikovic@<br>gmail.com
      link: mailto:marko.putnikovic@gmail.com
  follow:
    - name: GitHub
      link: http://github.com/putnich
    - name: LinkedIn
      link: http://linkedin.com/in/marko-putnikovic
    - name: Instagram
      link: http://instagram.com/de.putnich
      username: "@de.putnich"
    - name: Twitter
      link: http://twitter.com/putnich
      username: "@putnich"
  
# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
